apiVersion: v1
kind: Service
metadata:
  name: scheduler-extender
  namespace: kube-system
  labels:
    app: scheduler-extender
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - port: 39999
      name: http
      targetPort: 39999
  selector:
    app: scheduler-extender

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler-extender
    tier: backend
  name: scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-extender
      tier: backend
  template:
    metadata:
      labels:
        app: scheduler-extender
        tier: backend
    spec:
      containers:
      - command:
        - schd-extender
        image: litsky.com/litsky/scheduler-extender:0.0.1.beta1
        env:
        - name: LOG_LEVEL
          value: debug
        imagePullPolicy: IfNotPresent
        name: scheduler-extender
        ports:
        - containerPort: 39999
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: cluster-admin